// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/samriddhac/acme-flight/api/controller"
	"github.com/samriddhac/acme-flight/api/router"
	"github.com/samriddhac/acme-flight/config"
)

// Injectors from wire.go:

func InitializeRouter(cfg *config.Config, ctx *gin.Engine) router.Router {
	acmeFlightController := controller.NewAcmeFlightController()
	routerRouter := router.NewRouter(cfg, ctx, acmeFlightController)
	return routerRouter
}
